name: Deploy para GitHub Pages

on:
  push:
    branches: [0002]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Injetar Formspree URL
        env:
          FORMSPREE_URL: ${{ vars.FORMSPREE_URL }}
        run: |
          echo "URL encontrada: ${#FORMSPREE_URL}"

          sed -i "s|__FORMSPREE_URL__|$FORMSPREE_URL|g" docs/index.html

          grep "formspree.io" docs/index.html || true

      - name: Deploy para gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
