name: Deploy para GitHub Pages
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Injetar Formspree URL
        run: sed -i "s|__FORMSPREE_URL__|${{ secrets.FORMSPREE_URL }}|g" docs/index.html
      - name: Deploy para gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
